{% set version = '1.0.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-multilevelmod
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/multilevelmod_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/multilevelmod/multilevelmod_{{ version }}.tar.gz
  sha256: 53dc6c53a9aec1644a036c852351deaecd4fcf6176f2a2d85e7d73a00437016b

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-lme4
    - r-parsnip >=1.0.0
    - r-purrr
    - r-rlang
    - r-tibble
    - r-withr
  run:
    - r-base
    - r-dplyr
    - r-lme4
    - r-parsnip >=1.0.0
    - r-purrr
    - r-rlang
    - r-tibble
    - r-withr

test:
  commands:
    - $R -e "library('multilevelmod')"           # [not win]
    - "\"%R%\" -e \"library('multilevelmod')\""  # [win]

about:
  home: https://github.com/tidymodels/multilevelmod, http://multilevelmod.tidymodels.org/
  license: MIT
  summary: Bindings for hierarchical regression models for use with the 'parsnip' package. Models
    include longitudinal generalized linear models (Liang and Zeger, 1986) <doi:10.1093/biomet/73.1.13>,
    and mixed-effect models (Pinheiro and Bates) <doi:10.1007/978-1-4419-0318-1_1>.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - leej3

# Package: multilevelmod
# Title: Model Wrappers for Multi-Level Models
# Version: 1.0.0
# Authors@R: c( person("Max", "Kuhn", , "max@rstudio.com", role = c("aut"), comment = c(ORCID = "0000-0003-2402-136X")), person("Hannah", "Frick", , "hannah@rstudio.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-6049-5258")), person("RStudio", role = c("cph", "fnd")) )
# Description: Bindings for hierarchical regression models for use with the 'parsnip' package. Models include longitudinal generalized linear models (Liang and Zeger, 1986) <doi:10.1093/biomet/73.1.13>, and mixed-effect models (Pinheiro and Bates) <doi:10.1007/978-1-4419-0318-1_1>.
# License: MIT + file LICENSE
# URL: https://github.com/tidymodels/multilevelmod, http://multilevelmod.tidymodels.org/
# Depends: parsnip (>= 1.0.0), R (>= 2.10)
# Imports: dplyr, lme4, purrr, rlang, tibble, withr
# Suggests: covr, gee, ggplot2, knitr, nlme, rmarkdown, spelling, testthat, tidymodels
# VignetteBuilder: knitr
# Config/Needs/website: tidymodels/tidymodels, tidyverse/tidytemplate
# Encoding: UTF-8
# Language: en-US
# LazyData: true
# RoxygenNote: 7.2.0
# NeedsCompilation: no
# Packaged: 2022-06-17 11:38:17 UTC; hannah
# Author: Max Kuhn [aut] (<https://orcid.org/0000-0003-2402-136X>), Hannah Frick [aut, cre] (<https://orcid.org/0000-0002-6049-5258>), RStudio [cph, fnd]
# Maintainer: Hannah Frick <hannah@rstudio.com>
# Repository: CRAN
# Date/Publication: 2022-06-17 12:00:02 UTC
